### ISSUE TITLE
Adjust vertical alignment of button images

### ISSUE THREAD

**Issue by abrudz** [Dyalog/documentation-styles#8]
![Image](https://github.com/user-attachments/assets/338b93bc-2440-4cae-bf6f-81aeb8e72b5e)

Add
```css
img[height="20"]{vertical-align:text-bottom}
```
for

![Image](https://github.com/user-attachments/assets/70946940-7253-44af-a081-ed24627dde15)
